version: '2'
services:
  data:
    build: ./
  dnsmasq:
    cap_add:
      - NET_ADMIN
    image: svenv/dnsmasq
    ports:
      - 5353:53/udp
    restart: always
  openvpn:
    cap_add:
      - NET_ADMIN
    depends_on:
      - data
      - dnsmasq
    image: svenv/openvpn
    ports:
      - 1194:1194/udp
    restart: always
    volumes_from:
      - data
